-- Add dedicated audit actions for the Phase 10B Authorization Administration boundary.
-- Keep every historical physical enum value, including mapped Stock values.
ALTER TABLE `audit_logs`
    MODIFY `action` ENUM(
        'LOGIN_SUCCESS', 'LOGIN_FAILED', 'LOGOUT', 'PASSWORD_CHANGE', 'PASSWORD_RESET',
        'EMPLOYEE_CREATE', 'EMPLOYEE_UPDATE', 'EMPLOYEE_DELETE', 'EMPLOYEE_STATUS_CHANGE', 'EMPLOYEE_IMPORT',
        'TICKET_CREATE', 'TICKET_UPDATE', 'TICKET_STATUS_CHANGE', 'TICKET_ASSIGN', 'TICKET_COMMENT', 'TICKET_DELETE',
        'LEAVE_REQUEST_CREATE', 'LEAVE_REQUEST_APPROVE', 'LEAVE_REQUEST_REJECT', 'LEAVE_REQUEST_CANCEL',
        'LEAVE_REQUEST_CANCELLATION_REQUEST', 'LEAVE_REQUEST_CANCELLATION_CONFIRM',
        'LEAVE_REQUEST_NOT_TAKEN_REQUEST', 'LEAVE_REQUEST_NOT_TAKEN_CONFIRM',
        'USER_CREATE', 'USER_UPDATE', 'USER_DELETE', 'USER_ROLE_CHANGE',
        'TEAM_CREATE', 'TEAM_UPDATE', 'TEAM_DISABLE',
        'TEAM_MEMBER_ADD', 'TEAM_MEMBER_REMOVE', 'TEAM_MEMBER_ROLE_CHANGE',
        'TEAM_ROLE_CREATE', 'TEAM_ROLE_UPDATE', 'TEAM_ROLE_DISABLE',
        'TEAM_CAPABILITY_GRANT_UPDATE', 'TEAM_ROLE_CAPABILITY_GRANT_UPDATE',
        'USER_CAPABILITY_GRANT_ADD', 'USER_CAPABILITY_GRANT_REMOVE',
        'STOCK_ITEM_CREATE', 'STOCK_ITEM_UPDATE', 'STOCK_ITEM_DELETE', 'STOCK_ADJUST',
        'STOCK_REQUEST_CREATE', 'STOCK_REQUEST_APPROVE', 'STOCK_REQUEST_REJECT',
        'STOCK_CATEGORY_CREATE', 'STOCK_CATEGORY_DELETE', 'SETTINGS_UPDATE', 'DATA_EXPORT', 'EMAIL_REQUEST',
        'ROUTINE_TASK_CREATE', 'ROUTINE_TASK_UPDATE', 'ROUTINE_TASK_DEACTIVATE', 'ROUTINE_TASK_DELETE',
        'ROUTINE_OCCURRENCE_REASSIGN', 'ROUTINE_OCCURRENCE_DUE_DATE_CHANGE',
        'ROUTINE_IMPORT_UPLOAD', 'ROUTINE_IMPORT_ROW_UPDATE', 'ROUTINE_IMPORT_APPLY', 'ROUTINE_IMPORT_CANCEL'
    ) NOT NULL;

