-- Expand: NULL identifies rows created by the old app during deployment.
ALTER TABLE email_requests
  ADD COLUMN documentSystemDecision ENUM('UNDECIDED','NOT_REQUIRED','REQUIRED') NULL,
  ADD COLUMN sharedDriveDecision ENUM('UNDECIDED','NOT_REQUIRED','REQUIRED') NULL,
  ADD COLUMN accessVersion INTEGER NOT NULL DEFAULT 1;

UPDATE email_requests SET
  documentSystemDecision = CASE WHEN needsDocumentSystem = true THEN 'REQUIRED' ELSE 'NOT_REQUIRED' END,
  sharedDriveDecision = CASE WHEN sharedDriveAccess IS NOT NULL AND JSON_LENGTH(sharedDriveAccess) > 0 THEN 'REQUIRED' ELSE 'NOT_REQUIRED' END;

CREATE TABLE email_request_access_changes (
  id INTEGER NOT NULL AUTO_INCREMENT,
  emailRequestId INTEGER NOT NULL,
  actorId INTEGER NOT NULL,
  accessVersion INTEGER NOT NULL,
  `before` JSON NOT NULL,
  `after` JSON NOT NULL,
  createdAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE INDEX email_request_access_changes_emailRequestId_accessVersion_key (emailRequestId, accessVersion),
  CONSTRAINT email_request_access_changes_emailRequestId_fkey FOREIGN KEY (emailRequestId) REFERENCES email_requests(id) ON DELETE RESTRICT ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- Append only; preserve all historical enum values.
ALTER TABLE notification_outbox MODIFY type ENUM('TICKET_CREATED','TICKET_UPDATED','TICKET_CREATED_IN_APP','TICKET_CREATED_LINE','TICKET_CREATED_EMAIL_REPORTER','TICKET_CREATED_EMAIL_IT','TICKET_UPDATED_IN_APP_REPORTER','TICKET_UPDATED_EMAIL_REPORTER','TICKET_UPDATED_LINE','TICKET_COMMENT_IN_APP','EMAIL_REQUEST','LEAVE_ACTION','LEAVE_RESULT','LEAVE_CANCELLED','LEAVE_CANCELLATION_REQUESTED','LEAVE_CANCELLED_AFTER_APPROVAL','LEAVE_NOT_TAKEN_REQUESTED','LEAVE_NOT_TAKEN_CONFIRMED','LEAVE_ACTION_LINE','LEAVE_RESULT_LINE','LEAVE_CANCELLED_LINE','LEAVE_CANCELLATION_REQUESTED_LINE','LEAVE_CANCELLED_AFTER_APPROVAL_LINE','LEAVE_NOT_TAKEN_REQUESTED_LINE','LEAVE_NOT_TAKEN_CONFIRMED_LINE','STOCK_REQUEST_LINE','STOCK_LOW_LINE','STOCK_REQUEST_RESULT_EMAIL','STOCK_REQUEST_RESULT_LINE','ROUTINE_REMINDER_IN_APP','ROUTINE_REMINDER_EMAIL','ROUTINE_REMINDER_LINE','ROUTINE_CONTRACT_EXPIRY_IN_APP','ROUTINE_CONTRACT_EXPIRY_EMAIL','ROUTINE_CONTRACT_EXPIRY_LINE','IT_TICKET_IN_APP','IT_TICKET_LINE','IT_TICKET_EMAIL','EMAIL_REQUEST_EMAIL','EMAIL_REQUEST_LINE','EMAIL_REQUEST_ACCESS_UPDATED') NOT NULL;
