-- AlterTable
ALTER TABLE `tickets`
    ADD COLUMN `deletedAt` DATETIME(3) NULL,
    ADD COLUMN `deletedById` INTEGER NULL,
    ADD COLUMN `deleteReason` VARCHAR(500) NULL;

CREATE INDEX `tickets_deletedById_fkey` ON `tickets`(`deletedById`);

ALTER TABLE `tickets`
    ADD CONSTRAINT `tickets_deletedById_fkey`
    FOREIGN KEY (`deletedById`) REFERENCES `users`(`id`)
    ON DELETE SET NULL ON UPDATE CASCADE;

-- AlterEnum
ALTER TABLE `audit_logs` MODIFY `action` ENUM(
    'LOGIN_SUCCESS', 'LOGIN_FAILED', 'LOGOUT', 'PASSWORD_CHANGE',
    'PASSWORD_RESET', 'EMPLOYEE_CREATE', 'EMPLOYEE_UPDATE',
    'EMPLOYEE_DELETE', 'EMPLOYEE_STATUS_CHANGE', 'EMPLOYEE_IMPORT',
    'TICKET_CREATE', 'TICKET_UPDATE', 'TICKET_STATUS_CHANGE',
    'TICKET_ASSIGN', 'TICKET_COMMENT', 'TICKET_DELETE',
    'LEAVE_REQUEST_CREATE', 'LEAVE_REQUEST_APPROVE',
    'LEAVE_REQUEST_REJECT', 'LEAVE_REQUEST_CANCEL',
    'LEAVE_REQUEST_NOT_TAKEN_REQUEST', 'LEAVE_REQUEST_NOT_TAKEN_CONFIRM',
    'USER_CREATE', 'USER_UPDATE', 'USER_DELETE', 'USER_ROLE_CHANGE',
    'STOCK_ITEM_CREATE', 'STOCK_ITEM_UPDATE', 'STOCK_ITEM_DELETE',
    'STOCK_ADJUST', 'STOCK_REQUEST_CREATE', 'STOCK_REQUEST_APPROVE',
    'STOCK_REQUEST_REJECT', 'STOCK_CATEGORY_CREATE',
    'STOCK_CATEGORY_DELETE', 'SETTINGS_UPDATE', 'DATA_EXPORT',
    'EMAIL_REQUEST'
) NOT NULL;
