import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { SessionProvider } from "../components/auth/SessionProvider";
import { SWRProvider } from "../components/providers/SWRProvider";

const googleSans = localFont({
    src: "../public/fonts/GoogleSans-VariableFont.ttf",
    variable: "--font-google-sans",
    weight: "100 900",
});

export const metadata: Metadata = {
    title: "NHF IT Management System",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${googleSans.variable} antialiased`}>
                <SessionProvider>
                    <SWRProvider>{children}</SWRProvider>
                </SessionProvider>
            </body>
        </html>
    );
}
