-- AlterTable
ALTER TABLE `leave_requests`
    ADD COLUMN `emergencyReason` TEXT NULL,
    ADD COLUMN `specialReason` TEXT NULL,
    ADD COLUMN `overQuotaDays` DOUBLE NOT NULL DEFAULT 0,
    ADD COLUMN `notTakenReason` TEXT NULL,
    ADD COLUMN `notTakenRequestedAt` DATETIME(3) NULL,
    ADD COLUMN `notTakenConfirmedAt` DATETIME(3) NULL,
    ADD COLUMN `notTakenConfirmedById` INTEGER NULL,
    MODIFY `status` ENUM('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', 'NOT_TAKEN') NOT NULL DEFAULT 'PENDING';

-- CreateIndex
CREATE INDEX `leave_requests_notTakenRequestedAt_idx` ON `leave_requests`(`notTakenRequestedAt`);

-- AlterTable
ALTER TABLE `audit_logs` MODIFY `action` ENUM('LOGIN_SUCCESS', 'LOGIN_FAILED', 'LOGOUT', 'PASSWORD_CHANGE', 'PASSWORD_RESET', 'EMPLOYEE_CREATE', 'EMPLOYEE_UPDATE', 'EMPLOYEE_DELETE', 'EMPLOYEE_STATUS_CHANGE', 'EMPLOYEE_IMPORT', 'TICKET_CREATE', 'TICKET_UPDATE', 'TICKET_STATUS_CHANGE', 'TICKET_ASSIGN', 'TICKET_COMMENT', 'LEAVE_REQUEST_CREATE', 'LEAVE_REQUEST_APPROVE', 'LEAVE_REQUEST_REJECT', 'LEAVE_REQUEST_CANCEL', 'LEAVE_REQUEST_NOT_TAKEN_REQUEST', 'LEAVE_REQUEST_NOT_TAKEN_CONFIRM', 'USER_CREATE', 'USER_UPDATE', 'USER_DELETE', 'USER_ROLE_CHANGE', 'STOCK_ITEM_CREATE', 'STOCK_ITEM_UPDATE', 'STOCK_ITEM_DELETE', 'STOCK_ADJUST', 'STOCK_REQUEST_CREATE', 'STOCK_REQUEST_APPROVE', 'STOCK_REQUEST_REJECT', 'STOCK_CATEGORY_CREATE', 'STOCK_CATEGORY_DELETE', 'SETTINGS_UPDATE', 'DATA_EXPORT', 'EMAIL_REQUEST') NOT NULL;
