export const OUTBOX_NOTIFICATION_TYPES = [
    "EMAIL_REQUEST",
    "LEAVE_ACTION",
    "LEAVE_RESULT",
    "LEAVE_CANCELLED",
    "LEAVE_CANCELLATION_REQUESTED",
    "LEAVE_CANCELLED_AFTER_APPROVAL",
    "LEAVE_NOT_TAKEN_REQUESTED",
    "LEAVE_NOT_TAKEN_CONFIRMED",
    "LEAVE_ACTION_LINE",
    "LEAVE_RESULT_LINE",
    "LEAVE_CANCELLED_LINE",
    "LEAVE_CANCELLATION_REQUESTED_LINE",
    "LEAVE_CANCELLED_AFTER_APPROVAL_LINE",
    "LEAVE_NOT_TAKEN_REQUESTED_LINE",
    "LEAVE_NOT_TAKEN_CONFIRMED_LINE",
    "STOCK_REQUEST_LINE",
    "STOCK_LOW_LINE",
    "STOCK_REQUEST_RESULT_EMAIL",
    "STOCK_REQUEST_RESULT_LINE",
    "ROUTINE_REMINDER_IN_APP",
    "ROUTINE_REMINDER_EMAIL",
    "ROUTINE_REMINDER_LINE",
    "ROUTINE_CONTRACT_EXPIRY_IN_APP",
    "ROUTINE_CONTRACT_EXPIRY_EMAIL",
    "ROUTINE_CONTRACT_EXPIRY_LINE",
] as const;

export type OutboxNotificationType = (typeof OUTBOX_NOTIFICATION_TYPES)[number];

export const OUTBOX_STATUSES = [
    "PENDING",
    "PROCESSING",
    "SENT",
    "FAILED",
    "DEAD",
    "SUPERSEDED",
] as const;

export type OutboxStatus = (typeof OUTBOX_STATUSES)[number];

export const MAX_OUTBOX_ATTEMPTS = 3;
export const OUTBOX_RETRY_BASE_DELAY_MS = 60_000;
export const STALE_OUTBOX_PROCESSING_MINUTES = 10;

export function isOutboxNotificationType(
    value: string,
): value is OutboxNotificationType {
    return OUTBOX_NOTIFICATION_TYPES.includes(value as OutboxNotificationType);
}

