-- AlterTable
ALTER TABLE `notification_outbox`
    MODIFY `type` ENUM('TICKET_CREATED', 'TICKET_UPDATED', 'EMAIL_REQUEST', 'LEAVE_ACTION', 'LEAVE_RESULT', 'LEAVE_CANCELLED', 'LEAVE_NOT_TAKEN_REQUESTED', 'LEAVE_NOT_TAKEN_CONFIRMED', 'STOCK_REQUEST_LINE', 'STOCK_LOW_LINE') NOT NULL;

-- AlterTable
ALTER TABLE `notifications`
    ADD COLUMN `dedupeKey` VARCHAR(191) NULL,
    MODIFY `type` ENUM('TICKET_CREATED', 'NEW_COMMENT', 'TICKET_UPDATED', 'SYSTEM_ALERT', 'LEAVE_REQUESTED', 'LEAVE_APPROVED', 'LEAVE_REJECTED', 'LEAVE_CANCELLED', 'LEAVE_NOT_TAKEN_REQUESTED', 'LEAVE_NOT_TAKEN_CONFIRMED', 'STOCK_REQUEST_NEW', 'STOCK_APPROVED', 'STOCK_REJECTED') NOT NULL;

-- CreateIndex
CREATE UNIQUE INDEX `notifications_dedupeKey_key` ON `notifications`(`dedupeKey`);
