/**
 * Transitional client-facing facade retained for the Phase E2 presentation migration.
 */
export {
    LEAVE_ATTACHMENT_ACCEPTED_FORMATS,
    LEAVE_ATTACHMENT_ACCEPTED_TYPES,
    LEAVE_ATTACHMENT_MAX_BYTES,
    LEAVE_ATTACHMENT_MAX_FILES,
    LEAVE_ATTACHMENT_MAX_HEIGHT,
    LEAVE_ATTACHMENT_MAX_INPUT_PIXELS,
    LEAVE_ATTACHMENT_MAX_MB,
    LEAVE_ATTACHMENT_MAX_REQUEST_BYTES,
    LEAVE_ATTACHMENT_MAX_TOTAL_BYTES,
    LEAVE_ATTACHMENT_MAX_TOTAL_MB,
    LEAVE_ATTACHMENT_MAX_WIDTH,
    LEAVE_ATTACHMENT_ORPHAN_SAFETY_WINDOW_MS,
    LEAVE_ATTACHMENT_WEBP_QUALITY,
} from "@/modules/leave/client";
